pool:
  name: Default

trigger:
- main

variables:
  imageName: 'aks-demo-app'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'azureacraccess'
        repository: $(imageName)
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: Deploy
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'azure-spn-devops'
        azureResourceGroup: 'rg-aks-free-tier'
        kubernetesCluster: 'aks-free-cluster'
        namespace: default
        command: apply
        useConfigurationFile: true
        configuration: 'manifests/deployment.yaml'