apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1-azuredisk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pv1-azuredisk
  storageClassName: managed-csi
