apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: disk.csi.azure.com
  name: pvnew-azuredisk
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-csi
  csi:
    driver: disk.csi.azure.com
    volumeHandle: /subscriptions/60a4e683-430f-450e-aff4-3affdb8ddd50/resourceGroups/rg-aks-free-tier/providers/Microsoft.Compute/disks/myAKSDisk
    volumeAttributes:
      fsType: ext4