apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvcnew-azuredisk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pvnew-azuredisk
  storageClassName: managed-csi